name: test
run-name: Tests
on:
    workflow_dispatch:
    push:
jobs:
    test-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm run test
            - run: pnpm run lint
            - name: git
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"
                  git status
                  git tag
                  git describe
            - run: git tag
            - name: 'Get Latest tag'
              run: |
                  TAG=$(git tag | tail -1) && echo "latest_tag=$TAG" >> "$GITHUB_ENV"
            - run: |
                  echo "${{ env.latest_tag }}"
